version: '3.9'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: movielens_metabase
    ports:
      - "3000:3000"
    volumes:
      - metabase-data:/metabase-data
      - ./gcp-key.json:/app/gcp-key.json
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      GOOGLE_APPLICATION_CREDENTIALS: /app/gcp-key.json
    restart: always

volumes:
  metabase-data: